name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.5'
          cache: true
      - uses: anchore/sbom-action@v0
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  install-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make install script
        run: bash scripts/make-install.sh
      - name: Commit install script
        run: |
          git config user.name github-actions
          git config user.email github-action@github.com
          git add install.sh
          if ! git diff --staged --quiet; then
            git commit -m "$(git describe --tags --abbrev=0) install script update"
            echo "CHANGES_COMMITTED=true" >> $GITHUB_ENV
          else
            echo "No changes to commit"
            echo "CHANGES_COMMITTED=false" >> $GITHUB_ENV
          fi
      - name: Push install script
        run: |
          if [ "$CHANGES_COMMITTED" = "true" ]; then
            git push origin HEAD:main
          else
            echo "No changes to push"
          fi